const database = db.getSiblingDB("puchamon");

const DATA = {
  type_chart: [
    {
      _id: "Normal",
      superEffective: [],
      notVeryEffective: ["Rock", "Steel"],
      noEffect: ["Ghost"],
    },
    {
      _id: "Fire",
      superEffective: ["Grass", "Ice", "Bug", "Steel"],
      notVeryEffective: ["Fire", "Water", "Rock", "Dragon"],
      noEffect: [],
    },
    {
      _id: "Water",
      superEffective: ["Fire", "Ground", "Rock"],
      notVeryEffective: ["Water", "Grass", "Dragon"],
      noEffect: [],
    },
    {
      _id: "Electric",
      superEffective: ["Water", "Flying"],
      notVeryEffective: ["Electric", "Grass", "Dragon"],
      noEffect: ["Ground"],
    },
    {
      _id: "Grass",
      superEffective: ["Water", "Ground", "Rock"],
      notVeryEffective: [
        "Fire",
        "Grass",
        "Poison",
        "Flying",
        "Bug",
        "Dragon",
        "Steel",
      ],
      noEffect: [],
    },
    {
      _id: "Ice",
      superEffective: ["Grass", "Ground", "Flying", "Dragon"],
      notVeryEffective: ["Fire", "Water", "Ice", "Steel"],
      noEffect: [],
    },
    {
      _id: "Fighting",
      superEffective: ["Normal", "Ice", "Rock", "Dark", "Steel"],
      notVeryEffective: ["Poison", "Flying", "Psychic", "Bug"],
      noEffect: ["Ghost"],
    },
    {
      _id: "Poison",
      superEffective: ["Grass"],
      notVeryEffective: ["Poison", "Ground", "Rock", "Ghost"],
      noEffect: ["Steel"],
    },
    {
      _id: "Ground",
      superEffective: ["Fire", "Electric", "Poison", "Rock", "Steel"],
      notVeryEffective: ["Grass", "Bug"],
      noEffect: ["Flying"],
    },
    {
      _id: "Flying",
      superEffective: ["Grass", "Fighting", "Bug"],
      notVeryEffective: ["Electric", "Rock", "Steel"],
      noEffect: [],
    },
    {
      _id: "Psychic",
      superEffective: ["Fighting", "Poison"],
      notVeryEffective: ["Psychic", "Steel"],
      noEffect: ["Dark"],
    },
    {
      _id: "Bug",
      superEffective: ["Grass", "Psychic", "Dark"],
      notVeryEffective: [
        "Fire",
        "Fighting",
        "Poison",
        "Flying",
        "Ghost",
        "Steel",
      ],
      noEffect: [],
    },
    {
      _id: "Rock",
      superEffective: ["Fire", "Ice", "Flying", "Bug"],
      notVeryEffective: ["Fighting", "Ground", "Steel"],
      noEffect: [],
    },
    {
      _id: "Ghost",
      superEffective: ["Psychic", "Ghost"],
      notVeryEffective: ["Dark", "Steel"],
      noEffect: ["Normal"],
    },
    {
      _id: "Dragon",
      superEffective: ["Dragon"],
      notVeryEffective: ["Steel"],
      noEffect: [],
    },
    {
      _id: "Dark",
      superEffective: ["Psychic", "Ghost"],
      notVeryEffective: ["Fighting", "Dark", "Steel"],
      noEffect: [],
    },
    {
      _id: "Steel",
      superEffective: ["Ice", "Rock"],
      notVeryEffective: ["Fire", "Water", "Electric", "Steel"],
      noEffect: [],
    },
  ],

  weathers: [
    {
      _id: "rain",
      name: "Rain",
      defaultDuration: 5,
      effects: [
        {
          kind: "type_power_modifier",
          payload: { type: "Water", multiplier: 1.5 },
        },
        {
          kind: "type_power_modifier",
          payload: { type: "Fire", multiplier: 0.5 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "thunder", accuracy: 100 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "hurricane", accuracy: 100 },
        },
        {
          kind: "move_charge_modifier",
          payload: { moveId: "solar-beam", powerMultiplier: 0.5 },
        },
      ],
    },
    {
      _id: "sun",
      name: "Sun",
      defaultDuration: 5,
      effects: [
        {
          kind: "type_power_modifier",
          payload: { type: "Fire", multiplier: 1.5 },
        },
        {
          kind: "type_power_modifier",
          payload: { type: "Water", multiplier: 0.5 },
        },
        {
          kind: "move_charge_override",
          payload: { moveId: "solar-beam", skipCharge: true },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "thunder", accuracy: 50 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "hurricane", accuracy: 50 },
        },
      ],
    },
    {
      _id: "sandstorm",
      name: "Sandstorm",
      defaultDuration: 5,
      effects: [
        {
          kind: "end_turn_damage",
          payload: { ratio: 0.0625, immuneTypes: ["Rock", "Ground", "Steel"] },
        },
        {
          kind: "special_defense_modifier",
          payload: { targetTypes: ["Rock"], multiplier: 1.5 },
        },
      ],
    },
    {
      _id: "hail",
      name: "Hail",
      defaultDuration: 5,
      effects: [
        {
          kind: "end_turn_damage",
          payload: { ratio: 0.0625, immuneTypes: ["Ice"] },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "blizzard", accuracy: 100 },
        },
      ],
    },
  ],

  conditions: [
    {
      _id: "burn",
      name: "Burn",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "end_turn_damage", payload: { ratio: 0.125 } },
        { kind: "physical_attack_modifier", payload: { multiplier: 0.5 } },
      ],
    },
    {
      _id: "poison",
      name: "Poison",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "end_turn_damage", payload: { ratio: 0.125 } }],
    },
    {
      _id: "toxic",
      name: "Badly Poisoned",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "end_turn_bad_poison_damage", payload: { baseRatio: 0.0625 } },
      ],
    },
    {
      _id: "paralysis",
      name: "Paralysis",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "speed_modifier", payload: { multiplier: 0.25 } },
        { kind: "full_paralysis_chance", payload: { chance: 25 } },
      ],
    },
    {
      _id: "sleep",
      name: "Sleep",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "cannot_move", payload: {} }],
    },
    {
      _id: "freeze",
      name: "Freeze",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "cannot_move", payload: {} }],
    },
    {
      _id: "confusion",
      name: "Confusion",
      category: "volatile",
      defaultDuration: null,
      effects: [{ kind: "self_hit_chance", payload: { chance: 33 } }],
    },
    {
      _id: "flinch",
      name: "Flinch",
      category: "volatile",
      defaultDuration: 1,
      effects: [{ kind: "skip_action", payload: {} }],
    },
    {
      _id: "protect",
      name: "Protect",
      category: "volatile",
      defaultDuration: 1,
      effects: [{ kind: "block_protectable_moves", payload: {} }],
    },
  ],

  move_effects: [
    {
      _id: "fx-damage-single",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: 1 },
    },
    {
      _id: "fx-damage-multi-2-5",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: { mode: "random_range", min: 2, max: 5 } },
    },
    {
      _id: "fx-damage-special-def-target",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: 1, useTargetDefenseStat: "def" },
    },
    {
      _id: "fx-burn-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-burn-30",
      kind: "apply_major_status",
      target: "target",
      chance: 30,
      order: 2,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-burn-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 1,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-freeze-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "freeze" },
    },
    {
      _id: "fx-para-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "paralysis" },
    },
    {
      _id: "fx-para-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 2,
      payload: { conditionId: "paralysis" },
    },
    {
      _id: "fx-toxic-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 1,
      payload: { conditionId: "toxic" },
    },
    {
      _id: "fx-flinch-30",
      kind: "apply_volatile_status",
      target: "target",
      chance: 30,
      order: 2,
      payload: { conditionId: "flinch", duration: 1 },
    },
    {
      _id: "fx-stat-def-down1-target-chance20",
      kind: "modify_stat",
      target: "target",
      chance: 20,
      order: 2,
      payload: { changes: [{ stat: "def", stages: -1 }] },
    },
    {
      _id: "fx-stat-spa-down2-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spa", stages: -2 }] },
    },
    {
      _id: "fx-set-stealth-rock",
      kind: "set_hazard",
      target: "foe_side",
      chance: 100,
      order: 1,
      payload: { hazardId: "stealth-rock", layers: 1, maxLayers: 1 },
    },
    {
      _id: "fx-set-spikes",
      kind: "set_hazard",
      target: "foe_side",
      chance: 100,
      order: 1,
      payload: { hazardId: "spikes", layers: 1, maxLayers: 3 },
    },
    {
      _id: "fx-rapid-spin-cleanup",
      kind: "remove_hazard",
      target: "ally_side",
      chance: 100,
      order: 2,
      payload: {
        hazardIds: ["spikes", "toxic-spikes", "stealth-rock"],
      },
    },
    {
      _id: "fx-protect",
      kind: "protect",
      target: "self",
      chance: 100,
      order: 1,
      payload: { duration: 1 },
    },
    {
      _id: "fx-recover-50",
      kind: "heal_hp",
      target: "self",
      chance: 100,
      order: 1,
      payload: { ratio: 0.5 },
    },
    {
      _id: "fx-stat-atk-up2-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "atk", stages: 2 }] },
    },
    {
      _id: "fx-stat-spa-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spa", stages: 1 }] },
    },
    {
      _id: "fx-stat-spd-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: 1 }] },
    },
    {
      _id: "fx-stat-spe-down1-target",
      kind: "modify_stat",
      target: "target",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spe", stages: -1 }] },
    },
    {
      _id: "fx-stat-spd-down1-target-chance20",
      kind: "modify_stat",
      target: "target",
      chance: 20,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: -1 }] },
    },
    {
      _id: "fx-stat-spd-down1-target-chance10",
      kind: "modify_stat",
      target: "target",
      chance: 10,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: -1 }] },
    },
    {
      _id: "fx-sleep-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 2,
      payload: { conditionId: "sleep" }
    },
    {
      _id: "fx-stat-spe-down1-target",
      kind: "modify_stat",
      target: "target",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spe", stages: -1 }] },
    },
    {
      _id: "fx-stat-atk-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "atk", stages: 1 }] }
    },
    {
      _id: "fx-stat-spe-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spe", stages: 1 }] }
    }
  ],
  moves: [
    {
      _id: "stone-edge",
      name: "Stone Edge",
      type: "Rock",
      category: "Physical",
      power: 100,
      accuracy: 80,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "crunch",
      name: "Crunch",
      type: "Dark",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-def-down1-target-chance20"],
    },
    {
      _id: "earthquake",
      name: "Earthquake",
      type: "Ground",
      category: "Physical",
      power: 100,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "stealth-rock",
      name: "Stealth Rock",
      type: "Rock",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "foe_side",
      effectIds: ["fx-set-stealth-rock"],
    },
    {
      _id: "ice-beam",
      name: "Ice Beam",
      type: "Ice",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-freeze-10"],
    },
    {
      _id: "scald",
      name: "Scald",
      type: "Water",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-30"],
    },
    {
      _id: "toxic",
      name: "Toxic",
      type: "Poison",
      category: "Status",
      power: null,
      accuracy: 90,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-toxic-100"],
    },
    {
      _id: "toxic",
      name: "Toxic",
      type: "Poison",
      category: "Status",
      power: null,
      accuracy: 85,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-toxic-100"],
    },
    {
      _id: "protect",
      name: "Protect",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 10,
      priority: 4,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-protect"],
    },
    {
      _id: "hydro-pump",
      name: "Hydro Pump",
      type: "Water",
      category: "Special",
      power: 120,
      accuracy: 80,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "focus-blast",
      name: "Focus Blast",
      type: "Fighting",
      category: "Special",
      power: 120,
      accuracy: 70,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "spikes",
      name: "Spikes",
      type: "Ground",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "foe_side",
      effectIds: ["fx-set-spikes"],
    },
    {
      _id: "power-whip",
      name: "Power Whip",
      type: "Grass",
      category: "Physical",
      power: 120,
      accuracy: 85,
      pp: 10,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "iron-head",
      name: "Iron Head",
      type: "Steel",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-flinch-30"],
    },
    {
      _id: "thunder-wave",
      name: "Thunder Wave",
      type: "Electric",
      category: "Status",
      power: null,
      accuracy: 100,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-para-100"],
    },
    {
      _id: "draco-meteor",
      name: "Draco Meteor",
      type: "Dragon",
      category: "Special",
      power: 140,
      accuracy: 90,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spa-down2-user"],
    },
    {
      _id: "psyshock",
      name: "Psyshock",
      type: "Psychic",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-special-def-target"],
    },
    {
      _id: "surf",
      name: "Surf",
      type: "Water",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "rapid-spin",
      name: "Rapid Spin",
      type: "Normal",
      category: "Physical",
      power: 20,
      accuracy: 100,
      pp: 40,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-rapid-spin-cleanup"],
    },
    {
      _id: "thunderbolt",
      name: "Thunderbolt",
      type: "Electric",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-para-10"],
    },
    {
      _id: "recover",
      name: "Recover",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-recover-50"],
    },
    {
      _id: "iron-head",
      name: "Iron Head",
      type: "Steel",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-flinch-30"],
    },
    {
      _id: "x-scissor",
      name: "X-Scissor",
      type: "Bug",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "fire-punch",
      name: "Fire Punch",
      type: "Fire",
      category: "Physical",
      power: 75,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-10"],
    },
    {
      _id: "will-o-wisp",
      name: "Will-O-Wisp",
      type: "Fire",
      category: "Status",
      power: null,
      accuracy: 85,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-burn-100"],
    },
    {
      _id: "swords-dance",
      name: "Swords Dance",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up2-user"],
    },
    {
      _id: "mach-punch",
      name: "Mach Punch",
      type: "Fighting",
      category: "Physical",
      power: 40,
      accuracy: 100,
      pp: 30,
      priority: 1,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "bullet-seed",
      name: "Bullet Seed",
      type: "Grass",
      category: "Physical",
      power: 25,
      accuracy: 100,
      pp: 30,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-multi-2-5"],
    },
    {
      _id: "swords-dance",
      name: "Swords Dance",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up2-user"],
    },
    {
      _id: "thunder-wave",
      name: "Thunder Wave",
      type: "Electric",
      category: "Status",
      power: null,
      accuracy: 100,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-para-100"],
    },
    {
      _id: "low-sweep",
      name: "Low Sweep",
      type: "Fighting",
      category: "Physical",
      power: 65,
      accuracy: 100,
      pp: 20,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spe-down1-target"],
    },
    {
      _id: "seed-bomb",
      name: "Seed Bomb",
      type: "Grass",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "lava-plume",
      name: "Lava Plume",
      type: "Fire",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-30"],
    },
    {
      _id: "secret-sword",
      name: "Secret Sword",
      type: "Fighting",
      category: "Special",
      power: 85,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-special-def-target"],
    },
    {
      _id: "hidden-power-ice",
      name: "Hidden Power Ice",
      type: "Ice",
      category: "Special",
      power: 70,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "calm-mind",
      name: "Calm Mind",
      type: "Psychic",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-spa-up1-user", "fx-stat-spd-up1-user"],
    },
    {
      _id: "spore",
      name: "Spore",
      type: "Grass",
      category: "Status",
      power: null,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-sleep-100"],
    },
    {
      _id: "icy-wind",
      name: "Icy Wind",
      type: "Ice",
      category: "Special",
      power: 55,
      accuracy: 95,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "foe_side", // Afecta a todos los oponentes
      effectIds: ["fx-damage-single", "fx-stat-spe-down1-target"],
    },
    {
      _id: "shadow-ball",
      name: "Shadow Ball",
      type: "Ghost",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance20"],
    },
    {
      _id: "earth-power",
      name: "Earth Power",
      type: "Ground",
      category: "Special",
      power: 90,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance10"],
    },
    {
      _id: "dragon-dance",
      name: "Dragon Dance",
      type: "Dragon",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up1-user", "fx-stat-spe-up1-user"],
    },
    {
      _id: "ice-punch",
      name: "Ice Punch",
      type: "Ice",
      category: "Physical",
      power: 75,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-freeze-10"],
    },
  ],

  pokemons: [
    {
      _id: "tyranitar",
      name: "Tyranitar",
      types: ["Rock", "Dark"],
      baseStats: { hp: 100, atk: 134, def: 110, spa: 95, spd: 100, spe: 61 },
      abilities: ["sand-stream", "unnerve"],
    },
    {
      _id: "politoed",
      name: "Politoed",
      types: ["Water"],
      baseStats: { hp: 90, atk: 75, def: 75, spa: 90, spd: 100, spe: 70 },
      abilities: ["water-absorb", "damp", "drizzle"],
    },
    {
      _id: "ferrothorn",
      name: "Ferrothorn",
      types: ["Grass", "Steel"],
      baseStats: { hp: 74, atk: 94, def: 131, spa: 54, spd: 116, spe: 20 },
      abilities: ["iron-barbs"],
    },
    {
      _id: "latios",
      name: "Latios",
      types: ["Dragon", "Psychic"],
      baseStats: { hp: 80, atk: 90, def: 80, spa: 130, spd: 110, spe: 110 },
      abilities: ["levitate"],
    },
    {
      _id: "starmie",
      name: "Starmie",
      types: ["Water", "Psychic"],
      baseStats: { hp: 60, atk: 75, def: 85, spa: 100, spd: 85, spe: 115 },
      abilities: ["illuminate", "natural-cure", "analytic"],
    },
    {
      _id: "jirachi",
      name: "Jirachi",
      types: ["Steel", "Psychic"],
      baseStats: { hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100 },
      abilities: ["serene-grace"],
    },
    {
      _id: "rotom-wash",
      name: "Rotom-Wash",
      types: ["Electric", "Water"],
      baseStats: { hp: 50, atk: 65, def: 107, spa: 105, spd: 107, spe: 86 },
      abilities: ["levitate"],
    },
    {
      _id: "breloom",
      name: "Breloom",
      types: ["Grass", "Fighting"],
      baseStats: { hp: 60, atk: 130, def: 80, spa: 60, spd: 60, spe: 70 },
      abilities: ["effect-spore", "poison-heal", "technician"],
    },
    {
      _id: "heatran",
      name: "Heatran",
      types: ["Fire", "Steel"],
      baseStats: { hp: 91, atk: 90, def: 106, spa: 130, spd: 106, spe: 77 },
      abilities: ["flash-fire"],
    },
    {
      _id: "keldeo",
      name: "Keldeo",
      types: ["Water", "Fighting"],
      baseStats: { hp: 91, atk: 72, def: 90, spa: 129, spd: 90, spe: 108 },
      abilities: ["justified"],
    },
  ],

  movesets: [
    {
      _id: "tyranitar-choice-band",
      pokemonId: "tyranitar",
      movesetName: "Choice Band",
      nature: "Jolly",
      ability: "sand-stream",
      item: "choice-band",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["stone-edge", "crunch", "ice-punch", "earthquake"]
    },
    {
      _id: "tyranitar-dragon-dance",
      pokemonId: "tyranitar",
      movesetName: "Dragon Dance",
      nature: "Jolly",
      ability: "sand-stream",
      item: "chople-berry",
      evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
      moves: ["dragon-dance", "stone-edge", "earthquake", "ice-punch"]
    },
    {
      _id: "politoed-defensive",
      pokemonId: "politoed",
      movesetName: "Defensive Rain Setter",
      nature: "Bold",
      ability: "drizzle",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 252, spa: 0, spd: 8, spe: 0 },
      moves: ["scald", "toxic", "ice-beam", "protect"]
    },
    {
      _id: "politoed-choice-specs",
      pokemonId: "politoed",
      movesetName: "Choice Specs",
      nature: "Modest",
      ability: "drizzle",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["hydro-pump", "scald", "ice-beam", "focus-blast"]
    },
    {
      _id: "ferrothorn-spikes",
      pokemonId: "ferrothorn",
      movesetName: "Spikes Support",
      nature: "Relaxed",
      ability: "iron-barbs",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 88, spa: 0, spd: 168, spe: 0 },
      moves: ["spikes", "stealth-rock", "power-whip", "iron-head"]
    },
    {
      _id: "ferrothorn-stealth-rock",
      pokemonId: "ferrothorn",
      movesetName: "Stealth Rock Utility",
      nature: "Relaxed",
      ability: "iron-barbs",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 48, spa: 0, spd: 208, spe: 0 },
      moves: ["stealth-rock", "power-whip", "thunder-wave", "protect"]
    },
    {
      _id: "latios-choice-specs",
      pokemonId: "latios",
      movesetName: "Choice Specs",
      nature: "Timid",
      ability: "levitate",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["draco-meteor", "psyshock", "surf", "thunderbolt"]
    },
    {
      _id: "latios-choice-scarf",
      pokemonId: "latios",
      movesetName: "Choice Scarf",
      nature: "Timid",
      ability: "levitate",
      item: "choice-scarf",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["draco-meteor", "surf", "psyshock", "thunderbolt"]
    },
    {
      _id: "starmie-analytic-lo",
      pokemonId: "starmie",
      movesetName: "Analytic Life Orb Spinner",
      nature: "Timid",
      ability: "analytic",
      item: "life-orb",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["hydro-pump", "ice-beam", "thunderbolt", "rapid-spin"]
    },
    {
      _id: "starmie-leftovers-spin",
      pokemonId: "starmie",
      movesetName: "Recover Spinner",
      nature: "Timid",
      ability: "natural-cure",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 0, spa: 32, spd: 0, spe: 228 },
      moves: ["surf", "rapid-spin", "recover", "thunderbolt"]
    },
    {
      _id: "jirachi-choice-scarf",
      pokemonId: "jirachi",
      movesetName: "Choice Scarf",
      nature: "Jolly",
      ability: "serene-grace",
      item: "choice-scarf",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["iron-head", "x-scissor", "fire-punch", "thunderbolt"]
    },
    {
      _id: "jirachi-spdef-rocks",
      pokemonId: "jirachi",
      movesetName: "Specially Defensive Stealth Rock",
      nature: "Careful",
      ability: "serene-grace",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 224, spe: 32 },
      moves: ["iron-head", "toxic", "stealth-rock", "x-scissor"]
    },
    {
      _id: "rotom-wash-choice-scarf",
      pokemonId: "rotom-wash",
      movesetName: "Choice Scarf",
      nature: "Timid",
      ability: "levitate",
      item: "choice-scarf",
      evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 },
      moves: ["thunderbolt", "hydro-pump", "thunder-wave", "will-o-wisp"]
    },
    {
      _id: "rotom-wash-defensive",
      pokemonId: "rotom-wash",
      movesetName: "Defensive Pivot",
      nature: "Bold",
      ability: "levitate",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 252, spa: 0, spd: 8, spe: 0 },
      moves: ["thunderbolt", "hydro-pump", "shadow-ball", "will-o-wisp"]
    },
    {
      _id: "breloom-technician-sd",
      pokemonId: "breloom",
      movesetName: "Technician Swords Dance",
      nature: "Adamant",
      ability: "technician",
      item: "fighting-gem",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["mach-punch", "bullet-seed", "low-sweep", "swords-dance"]
    },
    {
      _id: "breloom-poison-heal",
      pokemonId: "breloom",
      movesetName: "Poison Heal SubPunch",
      nature: "Adamant",
      ability: "poison-heal",
      item: "toxic-orb",
      evs: { hp: 236, atk: 252, def: 0, spa: 0, spd: 20, spe: 0 },
      moves: ["mach-punch", "low-sweep", "seed-bomb", "spore"]
    },
    {
      _id: "heatran-spdef",
      pokemonId: "heatran",
      movesetName: "Specially Defensive",
      nature: "Calm",
      ability: "flash-fire",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 0, spa: 8, spd: 252, spe: 0 },
      moves: ["lava-plume", "toxic", "stealth-rock", "protect"]
    },
    {
      _id: "heatran-subtoxic",
      pokemonId: "heatran",
      movesetName: "SubToxic",
      nature: "Timid",
      ability: "flash-fire",
      item: "leftovers",
      evs: { hp: 8, atk: 0, def: 0, spa: 156, spd: 100, spe: 244 },
      moves: ["earth-power", "lava-plume", "toxic", "protect"]
    },
    {
      _id: "keldeo-choice-specs",
      pokemonId: "keldeo",
      movesetName: "Choice Specs",
      nature: "Timid",
      ability: "justified",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
      moves: ["hydro-pump", "surf", "secret-sword", "hidden-power-ice"]
    },
    {
      _id: "keldeo-calm-mind",
      pokemonId: "keldeo",
      movesetName: "Calm Mind",
      nature: "Timid",
      ability: "justified",
      item: "leftovers",
      evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
      moves: ["calm-mind", "surf", "secret-sword", "icy-wind"]
    }
  ]
};

// Limpia colecciones para evitar duplicados si lo ejecutas más de una vez.
[
  "type_chart",
  "weathers",
  "conditions",
  "move_effects",
  "moves",
  "pokemons",
  "movesets",
].forEach((name) => {
  database.getCollection(name).deleteMany({});
});

// Inserta datos.
database.type_chart.insertMany(DATA.type_chart);
database.weathers.insertMany(DATA.weathers);
database.conditions.insertMany(DATA.conditions);
database.move_effects.insertMany(DATA.move_effects);
database.moves.insertMany(DATA.moves);
database.pokemons.insertMany(DATA.pokemons);
database.movesets.insertMany(DATA.movesets);

print("Seed cargada correctamente en pokemon_battle_db");

db.moves.createIndex({ name: 1 }, { unique: true });
db.move_effects.createIndex({ kind: 1 });
db.conditions.createIndex({ category: 1 });
db.weathers.createIndex({ name: 1 }, { unique: true });
db.pokemons.createIndex({ name: 1 }, { unique: true });
db.movesets.createIndex({ pokemonId: 1 });
db.battles.createIndex({ status: 1, turn: 1 });
db.battle_instances.createIndex({ battleId: 1, trainerId: 1 });
db.battle_instances.createIndex({ battleId: 1, isActive: 1 });
