export const POKE_DATA = {
  type_chart: [
    {
      _id: "Normal",
      superEffective: [],
      notVeryEffective: ["Rock", "Steel"],
      noEffect: ["Ghost"],
    },
    {
      _id: "Fire",
      superEffective: ["Grass", "Ice", "Bug", "Steel"],
      notVeryEffective: ["Fire", "Water", "Rock", "Dragon"],
      noEffect: [],
    },
    {
      _id: "Water",
      superEffective: ["Fire", "Ground", "Rock"],
      notVeryEffective: ["Water", "Grass", "Dragon"],
      noEffect: [],
    },
    {
      _id: "Electric",
      superEffective: ["Water", "Flying"],
      notVeryEffective: ["Electric", "Grass", "Dragon"],
      noEffect: ["Ground"],
    },
    {
      _id: "Grass",
      superEffective: ["Water", "Ground", "Rock"],
      notVeryEffective: [
        "Fire",
        "Grass",
        "Poison",
        "Flying",
        "Bug",
        "Dragon",
        "Steel",
      ],
      noEffect: [],
    },
    {
      _id: "Ice",
      superEffective: ["Grass", "Ground", "Flying", "Dragon"],
      notVeryEffective: ["Fire", "Water", "Ice", "Steel"],
      noEffect: [],
    },
    {
      _id: "Fighting",
      superEffective: ["Normal", "Ice", "Rock", "Dark", "Steel"],
      notVeryEffective: ["Poison", "Flying", "Psychic", "Bug"],
      noEffect: ["Ghost"],
    },
    {
      _id: "Poison",
      superEffective: ["Grass"],
      notVeryEffective: ["Poison", "Ground", "Rock", "Ghost"],
      noEffect: ["Steel"],
    },
    {
      _id: "Ground",
      superEffective: ["Fire", "Electric", "Poison", "Rock", "Steel"],
      notVeryEffective: ["Grass", "Bug"],
      noEffect: ["Flying"],
    },
    {
      _id: "Flying",
      superEffective: ["Grass", "Fighting", "Bug"],
      notVeryEffective: ["Electric", "Rock", "Steel"],
      noEffect: [],
    },
    {
      _id: "Psychic",
      superEffective: ["Fighting", "Poison"],
      notVeryEffective: ["Psychic", "Steel"],
      noEffect: ["Dark"],
    },
    {
      _id: "Bug",
      superEffective: ["Grass", "Psychic", "Dark"],
      notVeryEffective: [
        "Fire",
        "Fighting",
        "Poison",
        "Flying",
        "Ghost",
        "Steel",
      ],
      noEffect: [],
    },
    {
      _id: "Rock",
      superEffective: ["Fire", "Ice", "Flying", "Bug"],
      notVeryEffective: ["Fighting", "Ground", "Steel"],
      noEffect: [],
    },
    {
      _id: "Ghost",
      superEffective: ["Psychic", "Ghost"],
      notVeryEffective: ["Dark", "Steel"],
      noEffect: ["Normal"],
    },
    {
      _id: "Dragon",
      superEffective: ["Dragon"],
      notVeryEffective: ["Steel"],
      noEffect: [],
    },
    {
      _id: "Dark",
      superEffective: ["Psychic", "Ghost"],
      notVeryEffective: ["Fighting", "Dark", "Steel"],
      noEffect: [],
    },
    {
      _id: "Steel",
      superEffective: ["Ice", "Rock"],
      notVeryEffective: ["Fire", "Water", "Electric", "Steel"],
      noEffect: [],
    },
  ],

  weathers: [
    {
      _id: "rain",
      name: "Rain",
      defaultDuration: 5,
      effects: [
        {
          kind: "type_power_modifier",
          payload: { type: "Water", multiplier: 1.5 },
        },
        {
          kind: "type_power_modifier",
          payload: { type: "Fire", multiplier: 0.5 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "thunder", accuracy: 100 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "hurricane", accuracy: 100 },
        },
        {
          kind: "move_charge_modifier",
          payload: { moveId: "solar-beam", powerMultiplier: 0.5 },
        },
      ],
    },
    {
      _id: "sun",
      name: "Sun",
      defaultDuration: 5,
      effects: [
        {
          kind: "type_power_modifier",
          payload: { type: "Fire", multiplier: 1.5 },
        },
        {
          kind: "type_power_modifier",
          payload: { type: "Water", multiplier: 0.5 },
        },
        {
          kind: "move_charge_override",
          payload: { moveId: "solar-beam", skipCharge: true },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "thunder", accuracy: 50 },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "hurricane", accuracy: 50 },
        },
      ],
    },
    {
      _id: "sandstorm",
      name: "Sandstorm",
      defaultDuration: 5,
      effects: [
        {
          kind: "end_turn_damage",
          payload: { ratio: 0.0625, immuneTypes: ["Rock", "Ground", "Steel"] },
        },
        {
          kind: "special_defense_modifier",
          payload: { targetTypes: ["Rock"], multiplier: 1.5 },
        },
      ],
    },
    {
      _id: "hail",
      name: "Hail",
      defaultDuration: 5,
      effects: [
        {
          kind: "end_turn_damage",
          payload: { ratio: 0.0625, immuneTypes: ["Ice"] },
        },
        {
          kind: "move_accuracy_override",
          payload: { moveId: "blizzard", accuracy: 100 },
        },
      ],
    },
  ],

  conditions: [
    {
      _id: "burn",
      name: "Quemado",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "end_turn_damage", payload: { ratio: 0.125 } },
        { kind: "physical_attack_modifier", payload: { multiplier: 0.5 } },
      ],
    },
    {
      _id: "poison",
      name: "Envenenado",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "end_turn_damage", payload: { ratio: 0.125 } }],
    },
    {
      _id: "toxic",
      name: "Gravemente Envenenado",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "end_turn_bad_poison_damage", payload: { baseRatio: 0.0625 } },
      ],
    },
    {
      _id: "paralysis",
      name: "Paralizado",
      category: "major",
      defaultDuration: null,
      effects: [
        { kind: "speed_modifier", payload: { multiplier: 0.5 } },
        { kind: "full_paralysis_chance", payload: { chance: 25 } },
      ],
    },
    {
      _id: "sleep",
      name: "Dormido",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "cannot_move", payload: {} }],
    },
    {
      _id: "freeze",
      name: "Congelado",
      category: "major",
      defaultDuration: null,
      effects: [{ kind: "cannot_move", payload: {} }],
    },
    {
      _id: "confusion",
      name: "Confundido",
      category: "volatile",
      defaultDuration: null,
      effects: [{ kind: "self_hit_chance", payload: { chance: 33 } }],
    },
    {
      _id: "flinch",
      name: "Aturdido",
      category: "volatile",
      defaultDuration: 1,
      effects: [{ kind: "skip_action", payload: {} }],
    },
    {
      _id: "protect",
      name: "Protegido",
      category: "volatile",
      defaultDuration: 1,
      effects: [{ kind: "block_protectable_moves", payload: {} }],
    },
  ],

  move_effects: [
    {
      _id: "fx-damage-single",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: 1 },
    },
    {
      _id: "fx-damage-multi-2-5",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: { mode: "random_range", min: 2, max: 5 } },
    },
    {
      _id: "fx-damage-special-def-target",
      kind: "damage",
      target: "target",
      chance: 100,
      order: 1,
      payload: { hits: 1, useTargetDefenseStat: "def" },
    },
    {
      _id: "fx-burn-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-burn-30",
      kind: "apply_major_status",
      target: "target",
      chance: 30,
      order: 2,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-burn-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 1,
      payload: { conditionId: "burn" },
    },
    {
      _id: "fx-freeze-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "freeze" },
    },
    {
      _id: "fx-para-10",
      kind: "apply_major_status",
      target: "target",
      chance: 10,
      order: 2,
      payload: { conditionId: "paralysis" },
    },
    {
      _id: "fx-para-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 2,
      payload: { conditionId: "paralysis" },
    },
    {
      _id: "fx-toxic-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 1,
      payload: { conditionId: "toxic" },
    },
    {
      _id: "fx-flinch-30",
      kind: "apply_volatile_status",
      target: "target",
      chance: 30,
      order: 2,
      payload: { conditionId: "flinch", duration: 1 },
    },
    {
      _id: "fx-stat-def-down1-target-chance20",
      kind: "modify_stat",
      target: "target",
      chance: 20,
      order: 2,
      payload: { changes: [{ stat: "def", stages: -1 }] },
    },
    {
      _id: "fx-stat-spa-down2-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spa", stages: -2 }] },
    },
    {
      _id: "fx-protect",
      kind: "protect",
      target: "self",
      chance: 100,
      order: 1,
      payload: { duration: 1 },
    },
    {
      _id: "fx-recover-50",
      kind: "heal_hp",
      target: "self",
      chance: 100,
      order: 1,
      payload: { ratio: 0.5 },
    },
    {
      _id: "fx-stat-atk-up2-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "atk", stages: 2 }] },
    },
    {
      _id: "fx-stat-spa-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spa", stages: 1 }] },
    },
    {
      _id: "fx-stat-spd-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: 1 }] },
    },
    {
      _id: "fx-stat-spe-down1-target",
      kind: "modify_stat",
      target: "target",
      chance: 100,
      order: 2,
      payload: { changes: [{ stat: "spe", stages: -1 }] },
    },
    {
      _id: "fx-stat-spd-down1-target-chance20",
      kind: "modify_stat",
      target: "target",
      chance: 20,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: -1 }] },
    },
    {
      _id: "fx-stat-spd-down1-target-chance10",
      kind: "modify_stat",
      target: "target",
      chance: 10,
      order: 2,
      payload: { changes: [{ stat: "spd", stages: -1 }] },
    },
    {
      _id: "fx-sleep-100",
      kind: "apply_major_status",
      target: "target",
      chance: 100,
      order: 2,
      payload: { conditionId: "sleep" }
    },
    {
      _id: "fx-stat-atk-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "atk", stages: 1 }] }
    },
    {
      _id: "fx-stat-spe-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spe", stages: 1 }] }
    },
    {
      _id: "fx-stat-def-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "def", stages: 1 }] }
    },
    {
      _id: "fx-stat-spe-down1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spe", stages: -1 }] }
    },
    {
      _id: "fx-stat-qd-up1-user",
      kind: "modify_stat",
      target: "self",
      chance: 100,
      order: 1,
      payload: { changes: [{ stat: "spa", stages: 1 }, { stat: "spd", stages: 1 }, { stat: "spe", stages: 1 }] }
    },
  ],
  moves: [
    {
      _id: "stone-edge",
      name: "Roca Afilada",
      type: "Rock",
      category: "Physical",
      power: 100,
      accuracy: 80,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "crunch",
      name: "Triturar",
      type: "Dark",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-def-down1-target-chance20"],
    },
    {
      _id: "earthquake",
      name: "Terremoto",
      type: "Ground",
      category: "Physical",
      power: 100,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "flash-cannon",
      name: "Foco Resplandor",
      type: "Steel",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance10"],
    },
    {
      _id: "ice-beam",
      name: "Rayo Hielo",
      type: "Ice",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-freeze-10"],
    },
    {
      _id: "scald",
      name: "Escaldar",
      type: "Water",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-30"],
    },
    {
      _id: "toxic",
      name: "Toxico",
      type: "Poison",
      category: "Status",
      power: null,
      accuracy: 90,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-toxic-100"],
    },
    {
      _id: "protect",
      name: "Protección",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 10,
      priority: 4,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-protect"],
    },
    {
      _id: "hydro-pump",
      name: "Hidro Bomba",
      type: "Water",
      category: "Special",
      power: 120,
      accuracy: 80,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "focus-blast",
      name: "Onda Certera",
      type: "Fighting",
      category: "Special",
      power: 120,
      accuracy: 70,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "power-whip",
      name: "Latigazo",
      type: "Grass",
      category: "Physical",
      power: 120,
      accuracy: 85,
      pp: 10,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "iron-head",
      name: "Cabeza de Hierro",
      type: "Steel",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-flinch-30"],
    },
    {
      _id: "thunder-wave",
      name: "Onda Trueno",
      type: "Electric",
      category: "Status",
      power: null,
      accuracy: 100,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-para-100"],
    },
    {
      _id: "draco-meteor",
      name: "Cometa Draco",
      type: "Dragon",
      category: "Special",
      power: 140,
      accuracy: 90,
      pp: 5,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spa-down2-user"],
    },
    {
      _id: "psyshock",
      name: "Psicocarga",
      type: "Psychic",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-special-def-target"],
    },
    {
      _id: "surf",
      name: "Surf",
      type: "Water",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "rapid-spin",
      name: "Giro Rápido",
      type: "Normal",
      category: "Physical",
      power: 20,
      accuracy: 100,
      pp: 40,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-rapid-spin-cleanup"],
    },
    {
      _id: "thunderbolt",
      name: "Rayo",
      type: "Electric",
      category: "Special",
      power: 95,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-para-10"],
    },
    {
      _id: "recover",
      name: "Recuperación",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-recover-50"],
    },
    {
      _id: "x-scissor",
      name: "Tijera-X",
      type: "Bug",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "fire-punch",
      name: "Puño Fuego",
      type: "Fire",
      category: "Physical",
      power: 75,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-10"],
    },
    {
      _id: "will-o-wisp",
      name: "Fuego Fatuo",
      type: "Fire",
      category: "Status",
      power: null,
      accuracy: 85,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-burn-100"],
    },
    {
      _id: "mach-punch",
      name: "Ultrapuño",
      type: "Fighting",
      category: "Physical",
      power: 40,
      accuracy: 100,
      pp: 30,
      priority: 1,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "bullet-seed",
      name: "Bala Semilla",
      type: "Grass",
      category: "Physical",
      power: 25,
      accuracy: 100,
      pp: 30,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-multi-2-5"],
    },
    {
      _id: "swords-dance",
      name: "Danza Espada",
      type: "Normal",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up2-user"],
    },
    {
      _id: "low-sweep",
      name: "Puntapié",
      type: "Fighting",
      category: "Physical",
      power: 65,
      accuracy: 100,
      pp: 20,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spe-down1-target"],
    },
    {
      _id: "seed-bomb",
      name: "Bomba Germen",
      type: "Grass",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "lava-plume",
      name: "Humareda",
      type: "Fire",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-30"],
    },
    {
      _id: "secret-sword",
      name: "Sable Místico",
      type: "Fighting",
      category: "Special",
      power: 85,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-special-def-target"],
    },
    {
      _id: "hidden-power-ice",
      name: "Poder Oculto",
      type: "Ice",
      category: "Special",
      power: 70,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "calm-mind",
      name: "Paz Mental",
      type: "Psychic",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-spa-up1-user", "fx-stat-spd-up1-user"],
    },
    {
      _id: "spore",
      name: "Espora",
      type: "Grass",
      category: "Status",
      power: null,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-sleep-100"],
    },
    {
      _id: "icy-wind",
      name: "Viento Helado",
      type: "Ice",
      category: "Special",
      power: 55,
      accuracy: 95,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "foe_side", // Afecta a todos los oponentes
      effectIds: ["fx-damage-single", "fx-stat-spe-down1-target"],
    },
    {
      _id: "shadow-ball",
      name: "Bola Sombra",
      type: "Ghost",
      category: "Special",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance20"],
    },
    {
      _id: "earth-power",
      name: "Tierra Viva",
      type: "Ground",
      category: "Special",
      power: 90,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance10"],
    },
    {
      _id: "dragon-dance",
      name: "Danza Dragón",
      type: "Dragon",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up1-user", "fx-stat-spe-up1-user"],
    },
    {
      _id: "ice-punch",
      name: "Puño Hielo",
      type: "Ice",
      category: "Physical",
      power: 75,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-freeze-10"],
    },
    {
      _id: "blaze-kick",
      name: "Patada Ígnea",
      type: "Fire",
      category: "Physical",
      power: 85,
      accuracy: 90,
      pp: 16,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-burn-10"],
    },
    {
      _id: "curse",
      name: "Maldición",
      type: "Ghost",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-atk-up1-user", "fx-stat-def-up1-user", "fx-stat-spe-down1-user"],
    },
    {
      _id: "waterfall",
      name: "Cascada",
      type: "Water",
      category: "Physical",
      power: 80,
      accuracy: 100,
      pp: 15,
      priority: 0,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-flinch-30"],
    },
    {
      _id: "bullet-punch",
      name: "Puño Bala",
      type: "Steel",
      category: "Physical",
      power: 40,
      accuracy: 100,
      pp: 30,
      priority: 1,
      makesContact: true,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single"],
    },
    {
      _id: "bug-buzz",
      name: "Zumbido",
      type: "Bug",
      category: "Special",
      power: 90,
      accuracy: 100,
      pp: 10,
      priority: 0,
      makesContact: false,
      protectable: true,
      target: "target",
      effectIds: ["fx-damage-single", "fx-stat-spd-down1-target-chance10"],
    },
    {
      _id: "quiver-dance",
      name: "Danza Aleteo",
      type: "Bug",
      category: "Status",
      power: null,
      accuracy: null,
      pp: 20,
      priority: 0,
      makesContact: false,
      protectable: false,
      target: "self",
      effectIds: ["fx-stat-qd-up1-user"],
    }
  ],

  pokemons: [
    {
      _id: "tyranitar",
      name: "Tyranitar",
      types: ["Rock", "Dark"],
      baseStats: { hp: 100, atk: 134, def: 110, spa: 95, spd: 100, spe: 61 },
      abilities: ["sand-stream", "unnerve"],
    },
    {
      _id: "politoed",
      name: "Politoed",
      types: ["Water"],
      baseStats: { hp: 90, atk: 75, def: 75, spa: 90, spd: 100, spe: 70 },
      abilities: ["water-absorb", "damp", "drizzle"],
    },
    {
      _id: "ferrothorn",
      name: "Ferrothorn",
      types: ["Grass", "Steel"],
      baseStats: { hp: 74, atk: 94, def: 131, spa: 54, spd: 116, spe: 20 },
      abilities: ["iron-barbs"],
    },
    {
      _id: "latios",
      name: "Latios",
      types: ["Dragon", "Psychic"],
      baseStats: { hp: 80, atk: 90, def: 80, spa: 130, spd: 110, spe: 110 },
      abilities: ["levitate"],
    },
    {
      _id: "starmie",
      name: "Starmie",
      types: ["Water", "Psychic"],
      baseStats: { hp: 60, atk: 75, def: 85, spa: 100, spd: 85, spe: 115 },
      abilities: ["illuminate", "natural-cure", "analytic"],
    },
    {
      _id: "jirachi",
      name: "Jirachi",
      types: ["Steel", "Psychic"],
      baseStats: { hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100 },
      abilities: ["serene-grace"],
    },
    {
      _id: "rotom-wash",
      name: "Rotom-Wash",
      types: ["Electric", "Water"],
      baseStats: { hp: 50, atk: 65, def: 107, spa: 105, spd: 107, spe: 86 },
      abilities: ["levitate"],
    },
    {
      _id: "breloom",
      name: "Breloom",
      types: ["Grass", "Fighting"],
      baseStats: { hp: 60, atk: 130, def: 80, spa: 60, spd: 60, spe: 70 },
      abilities: ["effect-spore", "poison-heal", "technician"],
    },
    {
      _id: "heatran",
      name: "Heatran",
      types: ["Fire", "Steel"],
      baseStats: { hp: 91, atk: 90, def: 106, spa: 130, spd: 106, spe: 77 },
      abilities: ["flash-fire"],
    },
    {
      _id: "keldeo",
      name: "Keldeo",
      types: ["Water", "Fighting"],
      baseStats: { hp: 91, atk: 72, def: 90, spa: 129, spd: 90, spe: 108 },
      abilities: ["justified"],
    },
    {
      _id: "blaziken",
      name: "Blaziken",
      types: ["Fire", "Fighting"],
      baseStats: { hp: 80, atk: 120, def: 70, spa: 110, spd: 70, spe: 80 },
      abilities: ["blaze", "speed-boost"],
    },
    {
      _id: "minccino",
      name: "Minccino",
      types: ["Normal"],
      baseStats: { hp: 55, atk: 50, def: 40, spa: 40, spd: 40, spe: 75 },
      abilities: ["cute-charm", "technician", "friend-guard"],
    },
    {
      _id: "dragonite",
      name: "Dragonite",
      types: ["Dragon", "Flying"],
      baseStats: { hp: 91, atk: 134, def: 95, spa: 100, spd: 100, spe: 80 },
      abilities: ["inner-focus", "multiscale"],
    },
    {
      _id: "garchomp",
      name: "Garchomp",
      types: ["Dragon", "Ground"],
      baseStats: { hp: 108, atk: 130, def: 95, spa: 80, spd: 85, spe: 102 },
      abilities: ["sand-veil", "rough-skin"],
    },
    {
      _id: "gengar",
      name: "Gengar",
      types: ["Ghost", "Poison"],
      baseStats: { hp: 60, atk: 65, def: 60, spa: 130, spd: 75, spe: 110 },
      abilities: ["levitate", "cursed-body"],
    },
    {
      _id: "gyarados",
      name: "Gyarados",
      types: ["Water", "Flying"],
      baseStats: { hp: 95, atk: 125, def: 79, spa: 60, spd: 100, spe: 81 },
      abilities: ["intimidate", "moxie"],
    },
    {
      _id: "scizor",
      name: "Scizor",
      types: ["Bug", "Steel"],
      baseStats: { hp: 70, atk: 130, def: 100, spa: 55, spd: 80, spe: 65 },
      abilities: ["swarm", "technician", "light-metal"],
    },
    {
      _id: "espeon",
      name: "Espeon",
      types: ["Psychic"],
      baseStats: { hp: 65, atk: 65, def: 60, spa: 130, spd: 95, spe: 110 },
      abilities: ["synchronize", "magic-bounce"],
    },
    {
      _id: "lucario",
      name: "Lucario",
      types: ["Fighting", "Steel"],
      baseStats: { hp: 70, atk: 110, def: 70, spa: 115, spd: 70, spe: 90 },
      abilities: ["steadfast", "inner-focus", "justified"],
    },
    {
      _id: "volcarona",
      name: "Volcarona",
      types: ["Bug", "Fire"],
      baseStats: { hp: 85, atk: 60, def: 71, spa: 135, spd: 105, spe: 100 },
      abilities: ["flame-body", "swarm"],
    },
    {
      _id: "alakazam",
      name: "Alakazam",
      types: ["Psychic"],
      baseStats: { hp: 55, atk: 50, def: 45, spa: 135, spd: 95, spe: 120 },
      abilities: ["synchronize", "inner-focus", "magic-guard"],
    },
    {
      _id: "metagross",
      name: "Metagross",
      types: ["Steel", "Psychic"],
      baseStats: { hp: 80, atk: 135, def: 130, spa: 95, spd: 90, spe: 70 },
      abilities: ["clear-body", "light-metal"],
    }
  ],

  movesets: [
    {
      _id: "tyranitar-choice-band",
      pokemonId: "tyranitar",
      movesetName: "Choice Band",
      nature: "Jolly",
      ability: "sand-stream",
      item: "choice-band",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["stone-edge", "crunch", "ice-punch", "earthquake"]
    },
    {
      _id: "tyranitar-dragon-dance",
      pokemonId: "tyranitar",
      movesetName: "Dragon Dance",
      nature: "Jolly",
      ability: "sand-stream",
      item: "chople-berry",
      evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
      moves: ["dragon-dance", "stone-edge", "earthquake", "ice-punch"]
    },
    {
      _id: "politoed-defensive",
      pokemonId: "politoed",
      movesetName: "Defensive Rain Setter",
      nature: "Bold",
      ability: "drizzle",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 252, spa: 0, spd: 8, spe: 0 },
      moves: ["scald", "toxic", "ice-beam", "protect"]
    },
    {
      _id: "politoed-choice-specs",
      pokemonId: "politoed",
      movesetName: "Choice Specs",
      nature: "Modest",
      ability: "drizzle",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["hydro-pump", "scald", "ice-beam", "focus-blast"]
    },
    {
      _id: "ferrothorn-utility",
      pokemonId: "ferrothorn",
      movesetName: "Status Utility Tank",
      nature: "Relaxed",
      ability: "iron-barbs",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 88, spa: 0, spd: 168, spe: 0 },
      moves: ["power-whip", "iron-head", "thunder-wave", "protect"]
    },
    {
      _id: "ferrothorn-curse",
      pokemonId: "ferrothorn",
      movesetName: "Curse Setup Tank",
      nature: "Sassy",
      ability: "iron-barbs",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 48, spa: 0, spd: 208, spe: 0 },
      moves: ["curse", "power-whip", "iron-head", "toxic"]
    },
    {
      _id: "latios-choice-specs",
      pokemonId: "latios",
      movesetName: "Choice Specs",
      nature: "Timid",
      ability: "levitate",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["draco-meteor", "psyshock", "surf", "thunderbolt"]
    },
    {
      _id: "latios-choice-scarf",
      pokemonId: "latios",
      movesetName: "Choice Scarf",
      nature: "Timid",
      ability: "levitate",
      item: "choice-scarf",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["draco-meteor", "surf", "psyshock", "thunderbolt"]
    },
    {
      _id: "starmie-analytic-lo",
      pokemonId: "starmie",
      movesetName: "Analytic Life Orb Spinner",
      nature: "Timid",
      ability: "analytic",
      item: "life-orb",
      evs: { hp: 0, atk: 0, def: 4, spa: 252, spd: 0, spe: 252 },
      moves: ["hydro-pump", "ice-beam", "thunderbolt", "rapid-spin"]
    },
    {
      _id: "starmie-leftovers-spin",
      pokemonId: "starmie",
      movesetName: "Recover Spinner",
      nature: "Timid",
      ability: "natural-cure",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 0, spa: 32, spd: 0, spe: 228 },
      moves: ["surf", "rapid-spin", "recover", "thunderbolt"]
    },
    {
      _id: "jirachi-choice-scarf",
      pokemonId: "jirachi",
      movesetName: "Choice Scarf",
      nature: "Jolly",
      ability: "serene-grace",
      item: "choice-scarf",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["iron-head", "x-scissor", "fire-punch", "thunderbolt"]
    },
    {
      _id: "jirachi-spdef-tank",
      pokemonId: "jirachi",
      movesetName: "Specially Defensive Tank",
      nature: "Careful",
      ability: "serene-grace",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 0, spa: 0, spd: 224, spe: 32 },
      moves: ["iron-head", "toxic", "protect", "x-scissor"]
    },
    {
      _id: "rotom-wash-choice-scarf",
      pokemonId: "rotom-wash",
      movesetName: "Choice Scarf",
      nature: "Timid",
      ability: "levitate",
      item: "choice-scarf",
      evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 },
      moves: ["thunderbolt", "hydro-pump", "thunder-wave", "will-o-wisp"]
    },
    {
      _id: "rotom-wash-defensive",
      pokemonId: "rotom-wash",
      movesetName: "Defensive Pivot",
      nature: "Bold",
      ability: "levitate",
      item: "leftovers",
      evs: { hp: 248, atk: 0, def: 252, spa: 0, spd: 8, spe: 0 },
      moves: ["thunderbolt", "hydro-pump", "shadow-ball", "will-o-wisp"]
    },
    {
      _id: "breloom-technician-sd",
      pokemonId: "breloom",
      movesetName: "Technician Swords Dance",
      nature: "Adamant",
      ability: "technician",
      item: "fighting-gem",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["mach-punch", "bullet-seed", "low-sweep", "swords-dance"]
    },
    {
      _id: "breloom-poison-heal",
      pokemonId: "breloom",
      movesetName: "Poison Heal SubPunch",
      nature: "Adamant",
      ability: "poison-heal",
      item: "toxic-orb",
      evs: { hp: 236, atk: 252, def: 0, spa: 0, spd: 20, spe: 0 },
      moves: ["mach-punch", "low-sweep", "seed-bomb", "spore"]
    },
    {
      _id: "heatran-offensive",
      pokemonId: "heatran",
      movesetName: "Offensive Wallbreaker",
      nature: "Timid",
      ability: "flash-fire",
      item: "choice-specs",
      evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
      moves: ["lava-plume", "earth-power", "flash-cannon", "hidden-power-ice"]
    },
    {
      _id: "heatran-subtoxic",
      pokemonId: "heatran",
      movesetName: "SubToxic",
      nature: "Timid",
      ability: "flash-fire",
      item: "leftovers",
      evs: { hp: 8, atk: 0, def: 0, spa: 156, spd: 100, spe: 244 },
      moves: ["earth-power", "lava-plume", "toxic", "protect"]
    },
    {
      _id: "keldeo-choice-specs",
      pokemonId: "keldeo",
      movesetName: "Choice Specs",
      nature: "Timid",
      ability: "justified",
      item: "choice-specs",
      evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
      moves: ["hydro-pump", "surf", "secret-sword", "hidden-power-ice"]
    },
    {
      _id: "keldeo-calm-mind",
      pokemonId: "keldeo",
      movesetName: "Calm Mind",
      nature: "Timid",
      ability: "justified",
      item: "leftovers",
      evs: { hp: 0, atk: 0, def: 0, spa: 252, spd: 4, spe: 252 },
      moves: ["calm-mind", "surf", "secret-sword", "icy-wind"]
    },
    {
      _id: "blaziken-speed-boost",
      pokemonId: "blaziken",
      movesetName: "Speed Boost",
      nature: "Adamant",
      ability: "speed-boost",
      item: "life-orb",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["blaze-kick", "protect", "stone-edge", "swords-dance"]
    },
    {
      _id: "minccino-utility",
      pokemonId: "minccino",
      movesetName: "Utility",
      nature: "Jolly",
      ability: "technician",
      item: "life-orb",
      evs: { hp: 0, atk: 252, def: 0, spa: 0, spd: 4, spe: 252 },
      moves: ["bullet-seed", "iron-head", "thunder-wave", "protect"]
    },
    {
      _id: "dragonite-dragon-dance",
      pokemonId: "dragonite",
      movesetName: "Dragon Dance",
      nature: "Adamant",
      ability: "multiscale",
      item: "lum-berry",
      evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
      moves: ["dragon-dance", "draco-meteor", "fire-punch", "earthquake"]
    },
    {
      _id: "garchomp-swords-dance",
      pokemonId: "garchomp",
      movesetName: "Swords Dance",
      nature: "Jolly",
      ability: "rough-skin",
      item: "yache-berry",
      evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
      moves: ["swords-dance", "earthquake", "stone-edge", "crunch"]
    },
    {
      _id: "gengar-offensive",
      pokemonId: "gengar",
      movesetName: "Offensive",
      nature: "Timid",
      ability: "levitate",
      item: "life-orb",
      evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
      moves: ["shadow-ball", "focus-blast", "thunderbolt", "will-o-wisp"]
    },
    {
      _id: "gyarados-dragon-dance",
      pokemonId: "gyarados",
      movesetName: "Dragon Dance",
      nature: "Jolly",
      ability: "intimidate",
      item: "leftovers",
      evs: { hp: 4, atk: 252, def: 0, spa: 0, spd: 0, spe: 252 },
      moves: ["dragon-dance", "waterfall", "earthquake", "stone-edge"]
    },
    {
      _id: "scizor-swords-dance",
      pokemonId: "scizor",
      movesetName: "Swords Dance",
      nature: "Adamant",
      ability: "technician",
      item: "life-orb",
      evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 },
      moves: ["swords-dance", "bullet-punch", "x-scissor", "protect"]
    },
    {
      _id: "espeon-calm-mind",
      pokemonId: "espeon",
      movesetName: "Calm Mind",
      nature: "Timid",
      ability: "magic-bounce",
      item: "leftovers",
      evs: { hp: 252, atk: 0, def: 4, spa: 0, spd: 0, spe: 252 },
      moves: ["calm-mind", "psyshock", "shadow-ball", "recover"]
    },
    {
      _id: "lucario-special",
      pokemonId: "lucario",
      movesetName: "Special Attacker",
      nature: "Timid",
      ability: "inner-focus",
      item: "life-orb",
      evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
      moves: ["focus-blast", "flash-cannon", "shadow-ball", "calm-mind"]
    },
    {
      _id: "volcarona-quiver-dance",
      pokemonId: "volcarona",
      movesetName: "Quiver Dance",
      nature: "Timid",
      ability: "flame-body",
      item: "leftovers",
      evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
      moves: ["quiver-dance", "lava-plume", "bug-buzz", "recover"]
    },
    {
      _id: "alakazam-offensive",
      pokemonId: "alakazam",
      movesetName: "Offensive",
      nature: "Timid",
      ability: "magic-guard",
      item: "life-orb",
      evs: { hp: 4, atk: 0, def: 0, spa: 252, spd: 0, spe: 252 },
      moves: ["psyshock", "focus-blast", "shadow-ball", "recover"]
    },
    {
      _id: "metagross-tank",
      pokemonId: "metagross",
      movesetName: "Tank",
      nature: "Adamant",
      ability: "clear-body",
      item: "leftovers",
      evs: { hp: 252, atk: 252, def: 4, spa: 0, spd: 0, spe: 0 },
      moves: ["iron-head", "earthquake", "stone-edge", "ice-punch"]
    }
  ]
};