"""Battle-wide domain rules and defaults."""

DEFAULT_BATTLE_LEVEL = 100
DEFAULT_BATTLE_IV = 31
MIN_DAMAGE_ROLL_PERCENT = 85
MAX_DAMAGE_ROLL_PERCENT = 100

# Entry Hazard Ratios
STEALTH_ROCK_BASE_RATIO = 1 / 8
SPIKES_LAYER_1 = 1
SPIKES_LAYER_1_RATIO = 1 / 8
SPIKES_LAYER_2 = 2
SPIKES_LAYER_2_RATIO = 1 / 6
SPIKES_LAYER_3_RATIO = 1 / 4

TOXIC_SPIKES_TOXIC_THRESHOLD = 2
