"""Battle-wide domain rules and defaults."""

DEFAULT_BATTLE_LEVEL = 100
DEFAULT_BATTLE_IV = 31
MIN_DAMAGE_ROLL_PERCENT = 85
MAX_DAMAGE_ROLL_PERCENT = 100
MAX_EV_PER_STAT = 252
MAX_TOTAL_EVS = 510
MIN_STAT_STAGE = -6
MAX_STAT_STAGE = 6
